### ISSUE TITLE
user-theme doesn't get enabled after installing

### ISSUE THREAD

**Issue by kapad** [brunelli/gnome-shell-extension-installer#11]
For some weird reason the user theme extension doesn't get enabled after installing. 

I've already tried the usual troubleshooting of logging out/in and restarting the gnome shell (Alt+F2, then "r", then enter) but this isn't helping. 

I've also tried to enable the extension directly using the gnome-shell-extension-tool (which this script uses internally), but this hasn't helped either. 

It's therefore, likely an issue with the extension and not this script, but I couldn't find the extension homepage on GH and thought I could ask here.

Any idea what the issue could be and how I could resolve it. I'm trying to script the installation of this extension and the installation of the specific theme that I want. (pop in my case).

**Comment by brunelli** [comment]
Just installed the extension with `gnome-shell-extension-installer 19`, restarted Shell and everything is working as expected. Are you sure the extension was properly installed?

Can you confirm that the file `$HOME/.local/share/gnome-shell/extensions/user-theme@gnome-shell-extensions.gcampax.github.com/metadata.json` exists?

If everything seems to be okay on the script's side you can open an issue in [GNOME's GitLab](https://gitlab.gnome.org/GNOME/gnome-shell-extensions).

**Comment by brunelli** [comment]
I was taking a look at your script and everything seems to be okay.

Just a quick suggestion: to avoid calling the `gnome-shell-extension-installer` more than once you can use an array.

```sh
EXTENSIONS=(
    19    # user themes
    964   # do not disturb button
    36    # lock keys
    1276  # night light slider
    826   # suspend button
)

$HOME/.local/bin/gnome-shell-extension-installer --yes ${EXTENSIONS[@]}
```

**Comment by kapad** [comment]
@brunelli - thanks for your response. I'm not really sure what the issue was here. When I dumped my dconf, I noticed that the active extensions array had the "user-themes" string, but not the unique extension name, i.e. "user-theme@gnome-shell-extensions.gcampax.github.com". 

But this too has now gotten fixed, and the array of active extensions has the full correct name for the user-themes extension. 

The array input is pretty cool. Will check it out. 

Thanks :)

**Comment by brunelli** [comment]
That sounds like a problem with the JSON parsing, maybe due to differences across sed versions, although I don't see any mention of "user-themes" in the extension data from EGO.

Are you able to reproduce this issue? If so, could you tell me what's the output of `sed --version`?
