### ISSUE TITLE
Exit with non-zero on missing dependency

### ISSUE THREAD

**Issue by bittner** [brunelli/gnome-shell-extension-installer#12]
When you use `gnome-shell-extension-installer` on a freshly-installed Ubuntu machine (which has, e.g., `curl` not yet installed) then the script exits, but the exit status is 0 (zero).

This is a problem when I use `gnome-shell-extension-installer` in scripts or Ansible playbooks: It remains unnoticed that installing shell extensions actually failed.

Fail loud
---------

It would be helpful if the script aborted in such a case, exiting with a non-zero exit code.

Alternative binary
------------

Specifically on Ubuntu, `wget` would be preinstalled. What would you think about falling back to `wget` in case `curl` is not installed? That could be a nice feature to reduce dependencies, or at least make them more flexible.

**Comment by brunelli** [comment]
> It would be helpful if the script aborted in such a case, exiting with a non-zero exit code.

Agreed.

> What would you think about falling back to wget in case curl is not installed?

I'd accept a PR implementing this, but I don't plan to work on this feature.

> That could be a nice feature to reduce dependencies

Not really. At least not when packaging.

> or at least make them more flexible.

That would be cool.

--------------

I'm currently thinking on getting rid of GNU Sed and Perl for json parsing and using jq.

But jq doesn't come in default installations, so this is holding me back, as I 1) don't want to maintain two parsers and 2) don't think gsei should have uncommon dependencies.

Curl, on the other hand, is pretty standard. But if Ubuntu thinks it shouldn't be default, well, maybe we should fallback to their alternative.

**Comment by bittner** [comment]
> I'd accept a PR implementing this, but I don't plan to work on this feature.

I'll try to look into it this week or so.

**Comment by bittner** [comment]
Sorry to tell you, but I figured that it makes more sense to integrate the entire feature set directly into the GNOME code base. See [gnome-shell issue #906](https://gitlab.gnome.org/GNOME/gnome-shell/issues/906) for details.

I hope it's okay that I suggested to take your code base as an example for the Python implementation.

**Comment by brunelli** [comment]
> Sorry to tell you, but I figured that it makes more sense to integrate the entire feature set directly into the GNOME code base

Don't worry. I just hope they figure it too (which I doubt will happen anytime soon).

> I hope it's okay that I suggested to take your code base as an example for the Python implementation.

Of course. More upstreamed features equals less code I have to maintain. Also, it's GPL.

**Comment by bittner** [comment]
> I just hope they figure it too (which I doubt will happen anytime soon).

I share those fears. But we have to try.

When you look at the [related discussion](https://gitlab.gnome.org/GNOME/gnome-shell/issues/906) you can probably figure there is a chance it won't happen. With rather lame excuses based on what seems technical ignorance. That's very sad. :worried:

Seems like the GNOME project is a very odd place when it comes to collaboration.

**Comment by bittner** [comment]
Collaboration issues aside ...

> GNOME Shell is a difficult platform to develop for.

From the [argos project](https://github.com/p-e-w/argos#acknowledgments). :laughing: (Sorry for going a bit off-topic!)

**Comment by brunelli** [comment]
Well, maybe you are looking for the wrong droids...

GNOME Tweaks [has the ability to update extensions](https://gitlab.gnome.org/GNOME/gnome-tweaks/commit/08f8cda3454eaa7c775353526632fa8bcd61d98a). So maybe open an issue/MR to make this feature available via CLI?

**Comment by bittner** [comment]
Aha, that looks interesting! Python :heart_eyes:

Though, I'm not sure if this can be used easily for automation. I would typically run Ansible or Puppet, and usually just in an SSH session, and for a machine (not typically just a single user). That's why your script is so useful.
