### ISSUE TITLE
Uninstall Extension

### ISSUE THREAD

**Issue by giovannicaligaris** [brunelli/gnome-shell-extension-installer#14]
Is there an uninstall command?

**Comment by brunelli** [comment]
> Is there an uninstall command?

`rm -rf "$HOME/.local/share/gnome-shell/extensions/$EXTENSION_UUID"`, where `$EXTENSION_UUID` is the UUID of the extension you want to uninstall.

**Comment by xpseudonym** [comment]
@brunelli or,
`rm -rf "/usr/local/share/gnome-shell/extensions/$EXTENSION_UUID"`
If installed with `sudo`
?

**Comment by brunelli** [comment]
> @brunelli or,
> `sudo rm -rf "/usr/local/share/gnome-shell/extensions/$EXTENSION_UUID"`
> If installed with `sudo`
> ?

Exactly!

**Comment by xpseudonym** [comment]
Thx
