### ISSUE TITLE
Automatic choose GNOME version

### ISSUE THREAD

**Issue by cirelli94** [brunelli/gnome-shell-extension-installer#6]
I see in this [script](https://github.com/tliron/install-gnome-themes/blob/master/install-gnome-themes) that you should be able to choose automatically the GNOME version.
I think it's a nice feature to add.

**Comment by brunelli** [comment]
It already does that if you don't set a version manually, so I'm closing the issue and you can reopen if you think I'm misunderstanding what you mean to say.
