### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by cirelli94** [brunelli/gnome-shell-extension-installer#7]
If you are interested in, Ubuntu needs curl to be manually installated to work.

**Comment by brunelli** [comment]
There's no Ubuntu package that I'm aware of. What are you suggesting?

The only available package is for Arch, and it has curl in it's dependency list.

**Comment by cirelli94** [comment]
Yes I know, just to say you could mention this in Manual Installation..

**Comment by brunelli** [comment]
Ok, I'll do it soon. Thanks for the report.

**Comment by brunelli** [comment]
Fixed with commit e2682e3, released with [v1.4.3](https://github.com/brunelli/gnome-shell-extension-installer/releases/tag/v1.4.3).
