### ISSUE TITLE
Check if already installed / update mode

### ISSUE THREAD

**Issue by gsantner** [brunelli/gnome-shell-extension-installer#8]
Please enable the script to check if the specified extension is already installed in the latest version. This can be done by checking `{/usr/share,~/.local/share}/gnome-shell/extensions/ID/metadata.json`["version"].

If both paths do not exist or there is a lower version number encountered, the extension should download and install it. If nothing is installed install it, if already installed in current version do nothing.

**Comment by brunelli** [comment]
>  if already installed in current version do nothing

If the user is explicitly telling the script to download and install the extension, why should it do nothing? Maybe he edited the files and want to reinstall the extension?

**Comment by gsantner** [comment]
I thought of some kind of "--update" option. The problem currently is, that if you want to keep around 15 extensions up to datee you have to wait a long time, but maybe there just one or two effectively outdated

**Comment by brunelli** [comment]
Fair enough. I don't have time to do it now, but maybe the best implementation would be to keep it the way it is now and add a `--update` switch which will download only new extensions/versions.

Would that be enough?

**Comment by gsantner** [comment]
Thanks for your time!
Yeah, update if udpateable. If there is no verison yet installed you can treat it as -1/0 so it also "updates"

**Comment by brunelli** [comment]
Well, good news!

I thought it would be easy to implement and took some time to work on it. What I described in the last comment is already done, but then I thought _"why not have the `--update` parameter get a list of installed extensions and check updates for all of them if no extension is passed to the command?"_ and that's what I'm coding right now. :stuck_out_tongue_winking_eye:

**Comment by gsantner** [comment]
Even better! :D 
So basically "--update-all" ? :+1:

**Comment by brunelli** [comment]
Just pushed a commit with a basic implementation of this. There are still two things I want fixed before releasing:

1. Better verbose when updating from git (if the directory is a git dir I'm using `git pull` to update -- I have lots of extensions installed from git);

2. Better handling of Shell version checking (maybe even disable it for GNOME Shell >= 3.20? -- considering `extension version validation` is disabled by default since then).

Let me know if you thing something more is missing.

Overall, I think this is a great feature I never new I missed. Thanks for reporting it.

**Comment by gsantner** [comment]
It checked all my extensions, but as everythingi is up2date I cant test it now :D.
Thanks for implementing

**Comment by gsantner** [comment]
@brunelli May I suggest another thing?
`--is-installed": Check if ID is installed. returns 0 if yes, else not. can also print out e.g. "is not installed" / "is installed".

I think it should be about 3 lines of code for determining (checking /usr/share/ and ~/.local/share)

**Comment by brunelli** [comment]
> I think it should be about 3 lines of code for determining (checking /usr/share/ and ~/.local/share)

Not really, because the extension ID (e.g. 307 for "Dash to Dock") is only found in EGO (it is not available in the `metadata.json` file). For this we'd have to use the UUID (e.g. "SmallPanelIcon@camporez.com"), and this would be useless, considering the UUID is only used in the folder name and inside `metadata.json`.

Of course it could be implemented by performing a request to get the extension info from EGO (https://extensions.gnome.org/extension-info/?pk=307), but this is not the kind of feature that should require a network connection to work.

**Comment by gsantner** [comment]
Oh, sorry with ID I exactly meant the package/emailname. Thats totally okay

**Comment by brunelli** [comment]
I just don't see this feature being useful. EGO doesn't display the extension's UUID in its page, so, if I had to find it, I'd have to locate its folder on the system, and then I'd already know if the extension is installed.

Maybe a `--list` or `--list-installed` parameter that would list all installed extensions?

**Comment by gsantner** [comment]
I think in this case it would be easier to determine by the folders said above than by parsing the output of  e.g. the suggested --list-installed

**Comment by brunelli** [comment]
Could you please describe exactly what would be your use case scenario?

**Comment by brunelli** [comment]
Better yet, could you do it in a new issue? :)

**Comment by gsantner** [comment]
Basically what I said on the very top.
To being able to install extensions if not installed, else update if updateable.

I am managing some computers with Gnome on it, and add some new devices from time to time. For my script, (calling yours) it is expected to not matter if already installed or not, the latest extension should just be installed. (without downloading everything again and again)

**Comment by brunelli** [comment]
> install extensions if not installed, else update if updateable

Isn't it exactly what `--update` does?

1. Get info from all extensions passed to the script.

2. Check if the extension is already installed...

    - If not installed: download and install it;
    
    - If installed in an older version: download and update it;
    
    - If installed in the same version: ignore.

**Comment by gsantner** [comment]
Does update take arguments? Thought it was just implemented to check for update of all currently installed extensions (without any argument)

**Comment by brunelli** [comment]
Yeah, it does.

> Thought it was just implemented to check for update of all currently installed extensions

This is the behavior only if no extension ID is passed. Maybe I should've left it more clear in the help.

**Comment by gsantner** [comment]
great, than I think this resolves everything! thanks
